[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mobile"
 
[dependencies]
uniffi = { version = "0.27.3", features = [ "cli" ] }
convnet-rust.workspace = true
serde_json = "1.0.117"
backtrace = "0.3.72"
android_logger = "0.13.3"
log = "0.4.21"
